// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLo1KaLu5qhm1JWxiUDipk8ma1cVdBNlU',
    appId: '1:1033167395771:web:008d067796083385b9029e',
    messagingSenderId: '1033167395771',
    projectId: 'khairak-qreep',
    authDomain: 'khairak-qreep.firebaseapp.com',
    storageBucket: 'khairak-qreep.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBou_PzAPQhHc3EU1JbLqI1X3bQEuLBDNQ',
    appId: '1:1033167395771:android:eb12f81b17d1e1a3b9029e',
    messagingSenderId: '1033167395771',
    projectId: 'khairak-qreep',
    storageBucket: 'khairak-qreep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvezG-0Gnvw1Gf9k-G1ncR898ONJoIJLs',
    appId: '1:1033167395771:ios:444535d6cb9299dab9029e',
    messagingSenderId: '1033167395771',
    projectId: 'khairak-qreep',
    storageBucket: 'khairak-qreep.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
